spring.application.name=mail-service
eureka.instance.prefer-ip-address=true

# Config Server
spring.config.import=optional:configserver:${CONFIG_URI:http://localhost:8888}
spring.profiles.active=${SPRING_PROFILES_ACTIVE:default}

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_URI:http://localhost:8761/eureka}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.main.allow-bean-definition-overriding=true
spring.cloud.compatibility-verifier.enabled=false
