# ================================
# Application
# ================================
spring.application.name=discovery-server
server.port=8761

# ================================
# Eureka Server Configuration
# ================================

# Bu sunucu kendini kaydetmesin (standalone mod)
eureka.client.register-with-eureka=false

# Bu sunucu ba?ka bir eureka'ya kay?t aramas?n
eureka.client.fetch-registry=false

# Eureka dashboard URL
eureka.client.service-url.defaultZone=${EUREKA_URI:http://localhost:8761/eureka}

# Eureka Server instance hostname
eureka.instance.hostname=${EUREKA_HOSTNAME:localhost}

# ================================
# Eureka Server Dashboard
# ================================

# Eureka UI dashboard aktif
spring.mvc.pathmatch.use-suffix-pattern=true

# ================================
# Logging
# ================================
logging.level.com.netflix.eureka=INFO
logging.level.com.netflix.discovery=INFO
