server.port=8085

# Database
spring.datasource.url=jdbc:postgresql://localhost:5436/cart_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.hostname=cart-service
eureka.instance.prefer-ip-address=true
eureka.instance.prefer-ip-address=true

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Exchange & Queue yap?land?rmas? (docs/04-events.md)
rabbitmq.exchange=marketplace.exchange
rabbitmq.queue.cart-clear=cart.clear.queue
rabbitmq.routing-key.cart-clear=cart.clear

spring.cloud.compatibility-verifier.enabled=false

