server.port=8085

# Database
spring.datasource.url=jdbc:postgresql://cart-postgres:5432/cart_db
spring.datasource.username=postgres
spring.datasource.password=${CART_DB_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Eureka
eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka
eureka.instance.hostname=cart-service
eureka.instance.prefer-ip-address=true

# RabbitMQ
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_USER:marketplace_admin}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:SaforyRabbit2024!}
rabbitmq.exchange=marketplace.exchange
rabbitmq.queue.cart-clear=cart.clear.queue
rabbitmq.routing-key.cart-clear=cart.clear

spring.cloud.compatibility-verifier.enabled=false

