server.port=8086

# Database
spring.datasource.url=jdbc:postgresql://localhost:5437/order_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.hostname=order-service
eureka.instance.prefer-ip-address=true

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
rabbitmq.exchange=marketplace.exchange

# Order-service publish
rabbitmq.queue.order-created=order.created.queue
rabbitmq.routing-key.order-created=order.created

# Order-service dinler
rabbitmq.queue.stock-reserved=stock.reserved.queue
rabbitmq.queue.stock-not-available=stock.not-available.queue
rabbitmq.queue.payment-success=payment.success.queue
rabbitmq.queue.payment-failed=payment.failed.queue
rabbitmq.routing-key.stock-reserved=stock.reserved
rabbitmq.routing-key.stock-not-available=stock.not-available
rabbitmq.routing-key.payment-triggered=payment.triggered
rabbitmq.routing-key.payment-success=payment.success
rabbitmq.routing-key.payment-failed=payment.failed

spring.cloud.compatibility-verifier.enabled=false

