server.port=8086

# Database
spring.datasource.url=jdbc:postgresql://order-postgres:5432/order_db
spring.datasource.username=postgres
spring.datasource.password=${ORDER_DB_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Eureka
eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka
eureka.instance.hostname=order-service
eureka.instance.prefer-ip-address=true

# RabbitMQ
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_USER:marketplace_admin}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:SaforyRabbit2024!}
rabbitmq.exchange=marketplace.exchange
rabbitmq.queue.order-created=order.created.queue
rabbitmq.routing-key.order-created=order.created
rabbitmq.queue.stock-reserved=stock.reserved.queue
rabbitmq.queue.stock-not-available=stock.not-available.queue
rabbitmq.queue.payment-success=payment.success.queue
rabbitmq.queue.payment-failed=payment.failed.queue
rabbitmq.routing-key.stock-reserved=stock.reserved
rabbitmq.routing-key.stock-not-available=stock.not-available
rabbitmq.routing-key.payment-triggered=payment.triggered
rabbitmq.routing-key.payment-success=payment.success
rabbitmq.routing-key.payment-failed=payment.failed

spring.cloud.compatibility-verifier.enabled=false

