server.port=8087

# Database
spring.datasource.url=jdbc:postgresql://localhost:5438/payment_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.hostname=payment-service
eureka.instance.prefer-ip-address=true

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
rabbitmq.exchange=marketplace.exchange
rabbitmq.queue.payment-success=payment.success.queue
rabbitmq.queue.payment-failed=payment.failed.queue
rabbitmq.routing-key.payment-success=payment.success
rabbitmq.routing-key.payment-failed=payment.failed

# mail-service'e bildirim göndermek için
rabbitmq.routing-key.notification-email=notification.email

spring.cloud.compatibility-verifier.enabled=false

# RabbitMQ ? payment-service'in dinledi?i queue
rabbitmq.queue.payment-triggered=payment.triggered.queue
rabbitmq.routing-key.payment-triggered=payment.triggered

# iyzico Sandbox Credentials
iyzico.api-key=sandbox-BmNWroICESk0qfN4gmlmfC3BMYLFDMXx
iyzico.secret-key=sandbox-ypwnVqp3CiIX8MNHNDx9oeluCU31XH5h
iyzico.base-url=https://sandbox-api.iyzipay.com


