server.port=8087

# Database
spring.datasource.url=jdbc:postgresql://payment-postgres:5432/payment_db
spring.datasource.username=postgres
spring.datasource.password=${PAYMENT_DB_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Eureka
eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka
eureka.instance.hostname=payment-service
eureka.instance.prefer-ip-address=true

# RabbitMQ
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_USER:marketplace_admin}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:SaforyRabbit2024!}
rabbitmq.exchange=marketplace.exchange
rabbitmq.queue.payment-success=payment.success.queue
rabbitmq.queue.payment-failed=payment.failed.queue
rabbitmq.routing-key.payment-success=payment.success
rabbitmq.routing-key.payment-failed=payment.failed
rabbitmq.routing-key.notification-email=notification.email
rabbitmq.queue.payment-triggered=payment.triggered.queue
rabbitmq.routing-key.payment-triggered=payment.triggered

# iyzico
iyzico.api-key=${IYZICO_API_KEY:sandbox-BmNWroICESk0qfN4gmlmfC3BMYLFDMXx}
iyzico.secret-key=${IYZICO_SECRET_KEY:sandbox-ypwnVqp3CiIX8MNHNDx9oeluCU31XH5h}
iyzico.base-url=${IYZICO_BASE_URL:https://sandbox-api.iyzipay.com}

spring.cloud.compatibility-verifier.enabled=false

