server.port=8089

# === DATABASE (PostgreSQL) ===
spring.datasource.url=jdbc:postgresql://localhost:5440/stock_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# === EUREKA ===
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.hostname=stock-service
eureka.instance.prefer-ip-address=true
eureka.instance.prefer-ip-address=true

# === RABBITMQ ===
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# RabbitMQ kuyruklar
rabbitmq.exchange=marketplace.exchange
rabbitmq.queue.order-created=order.created.queue
rabbitmq.queue.payment-success=payment.success.queue
rabbitmq.queue.payment-failed=payment.failed.queue
rabbitmq.queue.stock-reserved=stock.reserved.queue
rabbitmq.queue.stock-not-available=stock.not-available.queue
rabbitmq.routing-key.order-created=order.created
rabbitmq.routing-key.payment-success=payment.success
rabbitmq.routing-key.payment-failed=payment.failed
rabbitmq.routing-key.stock-reserved=stock.reserved
rabbitmq.routing-key.stock-not-available=stock.not-available

# Actuator
management.endpoints.web.exposure.include=*
management.endpoints.web.base-path=/actuator

spring.cloud.compatibility-verifier.enabled=false

