server.port=8082

# Database
spring.datasource.url=jdbc:postgresql://user-postgres:5432/user_db
spring.datasource.username=postgres
spring.datasource.password=${USER_DB_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Eureka
eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka
eureka.instance.hostname=user-service
eureka.instance.prefer-ip-address=true

# RabbitMQ
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_USER:marketplace_admin}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:SaforyRabbit2024!}

spring.cloud.compatibility-verifier.enabled=false

